### ISSUE TITLE
Update Fody to 2.0

### ISSUE THREAD

**Issue by SimonCropp** [bcuff/AutoLazy#3]
Fody Version 2 is out and you will need to do an update for your adding to be usable with it

Specifically:

 * Update to the newest Fody.Cecil nuget
 * Change the min dependency ranged for Fody to be at least 2.0

**Comment by WenceyWang** [comment]
Please update Nuget Package.

**Comment by bcuff** [comment]
@WenceyWang published. I haven't test it so let me know if there are any issues. Thanks.
