### ISSUE TITLE
AutoLazy does not apply to nested classes?

### ISSUE THREAD

**Issue by qwertio** [bcuff/AutoLazy#5]
I have a class nested inside another class, and had a get-property with the Lazy attribute. While testing I saw AutoLazy behavior was not applied to it.

**example test program:**

class Program {
        static void Main(string[] args) {
            var outer = new OuterClass();
            Debug.WriteLine(outer.GetProperty);
            Debug.WriteLine(outer.GetProperty);

            var inner = new OuterClass.InnerClass();
            Debug.WriteLine(inner.GetProperty);
            Debug.WriteLine(inner.GetProperty);
        }
    }

    class OuterClass {
        [Lazy] public int GetProperty {
            get {
                Debug.WriteLine($"Running {nameof(OuterClass)}.{nameof(OuterClass.GetProperty)}");
                return 1;
            }
        }

        public class InnerClass {
            [Lazy] public int GetProperty {
                get {
                    Debug.WriteLine($"Running {nameof(InnerClass)}.{nameof(InnerClass.GetProperty)}");
                    return 2;
                }
            }
        }
    }

**output:**
Running OuterClass.GetProperty
1
1
Running InnerClass.GetProperty
2
Running InnerClass.GetProperty
2

**expected output:**
Running OuterClass.GetProperty
1
1
Running InnerClass.GetProperty
2
2

**Comment by bcuff** [comment]
@qwertio thanks for reporting. I'll look into it but I probably won't get to it for a week or so.

**Comment by bcuff** [comment]
Fixed in 2.2.1.

**Comment by qwertio** [comment]
thank you, for your work on a lib that helps me immensely!

**Comment by bcuff** [comment]
you're welcome.
